function mu3
%MU3 : 4° finestra di sintesi e di ottimizzazione MU
%
%
% Massimo Davini 02/05/99

% put delgraf instead of delete(findobj('tag','grafico'));
% 25/may/02 Giampy

global stack;
delgraf;
set(stack.temp.handles,'visible','off');
drawnow;

% enlarge text if java machine is running
jsz=stack.general.javasize;

sizetext=jsz/2+.6;pos1=[0.062 0.75 0.44 0.18];pos2=[0.062 0.51 0.44 0.12];

mu3(1)=uicontrol('style','Frame','units','normalized','position',[0.05 0.66 0.46 0.29],...
     'backgroundcolor',[1 1 1],'tag','h2');
%sizetit*2/3
mu3(2)=uicontrol('style','text','units','normalized','position',pos1,...
   'fontunits','normalized','fontsize',.22,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'foregroundcolor',[1 0 0],...
   'HorizontalAlignment','left','tag','h2',...
   'string','Do you want to express the weights of T or M using a derivative action on the plant?');

mu3(3)=uicontrol('style','radiobutton','units','normalized','position',[0.15 0.68 0.12 0.06],...
   'fontunits','normalized','fontsize',jsz/2+.65,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'value',1,'tag','deriva1',...
   'HorizontalAlignment','left','string','YES',...
   'callback','sldopt(1,''deriva1'',''deriva2'');');

mu3(4)=uicontrol('style','radiobutton','units','normalized','position',[0.3 0.68 0.12 0.06],...
   'fontunits','normalized','fontsize',jsz/2+.65,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'value',0,'tag','deriva2',...
   'HorizontalAlignment','left',...
   'string','NO','callback','sldopt(2,''deriva1'',''deriva2'');');

drawnow;

mu3(5)=uicontrol('style','Frame','units','normalized','position',[0.05 0.22 0.46 0.43],...
     'backgroundcolor',[1 1 1],'tag','h2');
%sizetit
mu3(6)=uicontrol('style','text','units','normalized','position',pos2,...
   'fontunits','normalized','fontsize',.33,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'foregroundcolor',[1 0 0],...
   'HorizontalAlignment','left','tag','h2',...
   'string','Choose the function used to compute the controller :');

mu3(7)=uicontrol('style','radiobutton','units','normalized','position',[0.07 0.43 0.42 0.06],...
   'fontunits','normalized','fontsize',sizetext,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'value',1,'HorizontalAlignment','left',...
   'string',sprintf('musyne    (MU  tools)'),'tag','funz1',...
   'callback','sldopt(1,''funz1'',''funz2'');');
  
mu3(8)=uicontrol('style','radiobutton','units','normalized','position',[0.07 0.37 0.42 0.06],...
   'fontunits','normalized','fontsize',sizetext,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'value',0,'HorizontalAlignment','left',...
   'string',sprintf('musynl     (MU & LMI tools)'),'tag','funz2',...
   'callback','sldopt(2,''funz1'',''funz2'');');
  
mu3(9)=uicontrol('style','text','units','normalized','position',[0.06 0.25 0.44 0.08],...
   'fontunits','normalized','fontsize',jsz/1.5+.35,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'foregroundcolor',[1 0 0],...
   'HorizontalAlignment','left','tag','h2',...
   'string','The computation time could be long');
  
drawnow;

mu3(10)=uicontrol('style','push','unit','normalized','position',[0.57 0.85 0.38 0.1],...
   'fontunits','normalized','fontsize',jsz/3+.35,'fontweight','bold',...
   'Horizontalalignment','center','tag','BREG');

mu3(11)=uicontrol('style','push','unit','normalized','position',[0.05 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'string','BACK','Horizontalalignment','center','tag','BottBC',...
   'TooltipString','Back to the previous window','userdata',sprintf('feval(''back_syn'',''mu2'',%u)',length(stack.temp.handles)),...
   'callback',sprintf('if stack.general.K_flag messag(gcf,''kns'',''back'');else back_syn(''mu2'',%u);end;',length(stack.temp.handles)));
   
campi=['''integratori'',''pesi'',''sceltamatrici'',''bTo'',''bMo'',''bTi'',''bMi'',''flag'',''type'',''X1X2'',''plant'',''X1'',''X2'',''Fx'''];
mu3(12)=uicontrol('style','push','unit','normalized','position',[0.2 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'string','CLOSE','Horizontalalignment','center','userdata',sprintf('feval(''back_syn'',''syn0'',0,%s)',campi),...
   'TooltipString','Back to the main SYNTHESIS window','tag','BottBC',...
   'callback',sprintf('if stack.general.K_flag messag(gcf,''kns'',''close'');else back_syn(''syn0'',0,%s);end;',campi));
    
mu3(13)=uicontrol('style','push','unit','normalized','position',[0.39 0.05 0.275 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'TooltipString','Evaluate the computed Controller',...
   'Horizontalalignment','center','string','EVALUATION',...
   'callback','valuta;','tag','BEVAL','enable','off');

mu3(14)=uicontrol('style','push','unit','normalized','position',[0.675 0.05 0.275 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'TooltipString','Open the SIMULINK Closed-Loop-System',...
   'Horizontalalignment','center','string','SIMULATION',...
   'callback','simula;','tag','BSIMU','enable','off');

drawnow;

if isempty(stack.temp.pesi)
  set(mu3(10),'string','COMPUTE MU','callback','mu4;');
else
  set(mu3(10),'string','START OPTIMIZATION','callback','mu4opt;');
end;

stack.temp.handles=[stack.temp.handles,mu3];