function normgjw
%NORM(G(Jw,i,j))'s window
%
%
% Massimo Davini 15/05/99 --- revised 28/09/99

% put delgraf instead of delete(findobj('tag','grafico'));
% 25/may/02 Giampy

global stack;

delgraf;
set(stack.temp.handles,'visible','off');
drawnow;

% enlarge text if java machine is running
jsz=stack.general.javasize;
sizetext=jsz+0.7;

set(gcf,'Name',sprintf(' MIMO Tool : ANALYSIS %s --> Norm( G(JW,i,j) )',stack.general.model));

n(1)=uicontrol('style','push','unit','normalized','position',[0.05 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',0.35,'fontweight','bold',...
   'string','BACK','Horizontalalignment','center','tag','singval',...
   'TooltipString','Back to the Singular Values window');

callb=sprintf('back_ana(''singval'',%u);',length(stack.temp.handles));
set(n(1),'callback',callb);

n(2)=uicontrol('style','push','unit','normalized','position',[0.2 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',0.35,'fontweight','bold',...
   'string','CLOSE','Horizontalalignment','center',...
   'TooltipString','Back to the main ANALYSIS window',...
   'callback','back_ana(''ana0'',[]);');

n(3)=uicontrol('style','text','units','normalized','position',[0.45 0.085 0.21 0.05],...
   'fontunits','normalized','fontsize',sizetext,'fontweight','bold',...
   'backgroundcolor',[.6 .7 .9],'Horizontalalignment','right',...
   'string','Frequency : ');

n(4)=uicontrol('style','edit','units','normalized','position',[0.68 0.08 0.1 0.06],...
   'fontunits','normalized','fontsize',sizetext-0.1,'fontweight','bold',...
   'backgroundcolor',[1 1 0],'Horizontalalignment','left',...
   'TooltipString','Frequency for the new plot','tag','frequenza',...
   'string',num2str(0.001));

n(5)=uicontrol('style','push','unit','normalized','position',[0.83 0.05 0.12 0.12],...
   'fontunits','normalized','fontsize',0.35,'fontweight','bold',...
   'TooltipString','New plot',...
   'Horizontalalignment','center','string','PLOT',...
   'callback','normgjw1;');

stack.temp.handles=[stack.temp.handles,n];

drawnow;
normgjw1;