function hmix1
%mix1 : 2° finestra di sintesi e di ottimizzazione H-MIX
%
%
% Massimo Davini 01/06/99

 % put delgraf instead of delete(findobj('tag','grafico'));
% 25/may/02 Giampy

global stack;

if isempty(stack.temp.region) 
   stack.temp.region=stack.temp.dfl_region;
end;

delgraf;

handles=stack.temp.handles;
if ~isempty(findobj('tag','para'))
   x=length(handles);
   delete(stack.temp.handles(x-11:x));
   handles(x-11:x)=[];
   stack.temp.handles=handles;   
end;
set(handles,'visible','off');
drawnow;

% enlarge text if java machine is running
jsz=stack.general.javasize;

sizetext1=jsz+.65;

mix1(1)=uicontrol('style','frame','units','normalized','position',[0.1 0.32 0.8 0.53],...
    'backgroundcolor',[1 1 1],'visible','off','tag','mix1');
 
mix1(2)=uicontrol('style','text','units','normalized','position',[0.12 0.72 0.76 0.06],...
   'fontunits','normalized','fontsize',sizetext1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'HorizontalAlignment','center','foregroundcolor','red',...
   'visible','off','string','Which matrix do you want to minimize ?',...
   'tag','mix1');

mix1(3)=uicontrol('style','radiobutton','units','normalized','position',[0.15 0.6 0.2 0.06],...
   'fontunits','normalized','fontsize',sizetext1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','value',1,...
   'HorizontalAlignment','left','string',' [ To ; So ]',...
   'callback','sldopt(1,''opt1'',''opt2'');','tag','opt1');

mix1(4)=uicontrol('style','text','units','normalized','position',[0.15 0.54 0.7 0.06],...
   'fontunits','normalized','fontsize',sizetext1*0.8,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','HorizontalAlignment','left',...
   'string','      COMPLEMENTARY SENSITIVITY and SENSITIVITY','tag','mix1');

mix1(5)=uicontrol('style','radiobutton','units','normalized','position',[0.15 0.44 0.4 0.06],...
   'fontunits','normalized','fontsize',sizetext1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','HorizontalAlignment','left',...
   'string',' [ Mo ; So ]','tag','opt2',...
   'callback','sldopt(2,''opt1'',''opt2'');');

mix1(6)=uicontrol('style','text','units','normalized','position',[0.15 0.38 0.7 0.06],...
   'fontunits','normalized','fontsize',sizetext1*0.8,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','HorizontalAlignment','left',...
   'string','      CONTROL SENSITIVITY and SENSITIVITY','tag','mix1');
 
mix1(7)=uicontrol('style','push','unit','normalized','position',[0.05 0.05 0.14 0.12],...
    'fontunits','normalized','fontsize',.35,'fontweight','bold',...
    'string','BACK','Horizontalalignment','center','tag','mix1',...
    'TooltipString','Back to the previous window',...
    'callback',sprintf('back_syn(''mix0'',%u);',length(stack.temp.handles))); 
 
campi=['''integratori'',''pesi'',''dfl_region'',''region'',''new_param'',''type'',''X1X2'',''plant'',''x2'''];
mix1(8)=uicontrol('style','push','unit','normalized','position',[0.2 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'string','CLOSE','Horizontalalignment','center',...
   'TooltipString','Back to the main SYNTHESIS window',...
   'callback',sprintf('back_syn(''syn0'',0,%s);',campi),'tag','mix1');
 
mix1(9)=uicontrol('style','push','unit','normalized','position',[0.81 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'Horizontalalignment','center','string','NEXT','tag','mix1',...
   'TooltipString','Go to the next window','callback','hmix2');

set(mix1,'visible','on');
drawnow;

stack.temp.handles=[stack.temp.handles,mix1];