function avvio_1
%Crea la prima finestra di mimotool
%
%      avvio_1          
%
% Massimo Davini 12/05/99 --- revised 21/04/2000

global stack;

% enlarge text if java machine is running
jsz=stack.general.javasize;

Frame00=uicontrol('style','frame',...
   'units','normalized','position',[.05 .77 .9 .15],...
   'backgroundcolor',[1 1 1],'tag','first');

Title = uicontrol('style','text',...
   'unit','normalized','position',[.06 .785 .88 .1],...
   'backgroundColor',[1 1 1],'ForegroundColor',[1 0 0],...
   'fontunits','normalized','fontsize',.8,'fontweight','bold',...
   'Horizontalalignment','center','fontname','times new roman',...
   'string','MIMO TOOL','tag','first',...
   'fontangle','italic');

%-------------------------------
%----------TEXT & FRAME---------

FrameMod=uicontrol('style','frame',...
   'units','normalized','position',[0.05 0.6 0.4 0.075],...
   'backgroundcolor',[1 1 0.2],'tag','first');

TestoMod = uicontrol('style','text',...
   'unit','normalized','position',[0.055 0.61 0.39 0.051],...
   'fontunits','normalized','fontsize',.85+jsz/4,...
   'fontangle','italic','fontweight','bold',...
   'BackgroundColor',[1 1 0.2],'ForegroundColor',[0 0 0],...
   'Horizontalalignment','center','string','MODELING','tag','first');
%---
FrameAna=uicontrol('style','frame',...
   'units','normalized','position',[0.05 0.5 0.4 0.075],...
   'backgroundcolor',[1 1 0.2],'tag','first');

TestoAna = uicontrol('style','text',...
   'unit','normalized','position',[0.055 0.51 0.39 0.051],...
   'fontunits','normalized','fontsize',.85+jsz/4,...
   'fontangle','italic','fontweight','bold',...
   'BackgroundColor',[1 1 0.2],'ForegroundColor',[0 0 0],...
   'Horizontalalignment','center','string','ANALYSIS','tag','first');
%---
FrameSyn=uicontrol('style','frame',...
   'units','normalized','position',[0.05 0.4 0.4 0.075],...
   'backgroundcolor',[1 1 0.2],'tag','first');

TestoSyn = uicontrol('style','text',...
   'unit','normalized','position',[0.055 0.41 0.39 0.051],...
   'fontunits','normalized','fontsize',.85+jsz/4,...
   'fontangle','italic','fontweight','bold',...
   'BackgroundColor',[1 1 0.2],'ForegroundColor',[0 0 0],...
   'Horizontalalignment','center','string','SYNTHESIS','tag','first');
%---
FrameOpt=uicontrol('style','frame',...
   'units','normalized','position',[0.05 0.3 0.4 0.075],...
   'backgroundcolor',[1 1 0.2],'tag','first');

TestoOpt = uicontrol('style','text',...
   'unit','normalized','position',[0.055 0.31 0.39 0.051],...
   'fontunits','normalized','fontsize',.85+jsz/4,...
   'fontangle','italic','fontweight','bold','tag','first',...
   'BackgroundColor',[1 1 0.2],'ForegroundColor',[0 0 0],...
   'Horizontalalignment','center','string','OPTIMIZATION');
%---
FrameEva=uicontrol('style','frame',...
   'units','normalized','position',[0.05 0.2 0.4 0.075],...
   'backgroundcolor',[1 1 0.2],'tag','first');

TestoEva = uicontrol('style','text',...
   'unit','normalized','position',[0.055 0.21 0.39 0.051],...
   'fontunits','normalized','fontsize',.85+jsz/4,...
   'fontangle','italic','fontweight','bold','tag','first',...
   'BackgroundColor',[1 1 0.2],'ForegroundColor',[0 0 0],...
   'Horizontalalignment','center','string','EVALUATION');
%---
FrameSim=uicontrol('style','frame',...
   'units','normalized','position',[0.05 0.1 0.4 0.075],...
   'backgroundcolor',[1 1 .2],'tag','first');

TestoSim = uicontrol('style','text',...
   'unit','normalized','position',[0.055 0.11 0.39 0.051],...
   'fontunits','normalized','fontsize',.85+jsz/4,...
   'fontangle','italic','fontweight','bold','tag','first',...
   'BackgroundColor',[1 1 .2],'ForegroundColor',[0 0 0],...
   'Horizontalalignment','center','string','SIMULATION');

%--------------------------
%---------BOTTONI----------

FrameRB=uicontrol('style','frame',...
   'units','normalized','position',[0.5 0.4 0.45 0.275],...
   'backgroundcolor',[1 1 1],'tag','first');

check1 = uicontrol('style','checkbox',...
   'unit','normalized','position',[0.52 0.6 0.41 0.05],...
   'fontunits','normalized','fontsize',.6+jsz,'fontweight','bold',...
   'BackgroundColor',[1 1 1],'tag','first','enable','inactive',...
   'Horizontalalignment','center',...
   'string','LMI and Control Toolboxes');

check2 = uicontrol('style','checkbox',...
   'unit','normalized','position',[0.52 0.54 0.41 0.05],...
   'fontunits','normalized','fontsize',.6+jsz,'fontweight','bold',...
   'BackgroundColor',[1 1 1],'tag','first','enable','inactive',...
   'Horizontalalignment','center','string','Mu analysis\synthesis toolbox');

check3 = uicontrol('style','checkbox',...
   'unit','normalized','position',[0.52 0.48 0.41 0.05],...
   'fontunits','normalized','fontsize',.6+jsz,'fontweight','bold',...
   'BackgroundColor',[1 1 1],'tag','first','enable','inactive',...
   'Horizontalalignment','center','string','Robust control toolbox');

check4 = uicontrol('style','checkbox',...
   'unit','normalized','position',[0.52 0.42 0.41 0.05],...
   'fontunits','normalized','fontsize',.6+jsz,'fontweight','bold',...
   'BackgroundColor',[1 1 1],'tag','first','enable','inactive',...
   'Horizontalalignment','center','string','Optimization toolbox');

BottStart = uicontrol('style','push',...
   'unit','normalized','position',[0.5 0.25 0.45 0.12],...
   'fontunits','normalized','fontsize',0.35+jsz/2,'fontweight','bold',...
   'Horizontalalignment','center','Enable','off',...
   'string','START','tag','first',...
   'callback','delete(findobj(''tag'',''first''));modeling;');

BottHelp = uicontrol('style','push',...
   'unit','normalized','position',[0.5 0.1 0.2 0.12],...
   'fontunits','normalized','fontsize',0.35+jsz/2,'fontweight','bold',...
   'Horizontalalignment','center','string','HELP','tag','first',...
   'callback',['! ' which('helpdeskmvt.htm')]); 

BottExit = uicontrol('style','push',...
   'unit','normalized','position',[0.75 0.1 0.2 0.12],...
   'fontunits','normalized','fontsize',0.35+jsz/2,'fontweight','bold',...
   'Horizontalalignment','center','string','EXIT','tag','first',...
   'callback','esci;');
   
   
set(gcf,'visible','on');
drawnow;
pause(.5);

if ~isempty(ver('control')) & ~isempty(ver('lmi')) 
   set(check1,'value',1,'foregroundcolor','blue');
end;
pause(.2);

if ~isempty(ver('mutools')) 
   set(check2,'value',1,'foregroundcolor','blue');
end;
pause(.2);

if ~isempty(ver('robust')) 
   set(check3,'value',1,'foregroundcolor','blue');
end;
pause(.2);

if ~isempty(ver('optim')) 
   set(check4,'value',1,'foregroundcolor','blue');
end;
pause(.2);

versione=version;
vcell = regexp(versione,'\d+\.\d','match');
vnum=str2num(vcell{1});

if vnum > 7
    if ~isempty(ver('robust'))
        set(check1,'value',1,'foregroundcolor','blue');
        set(check2,'value',1,'foregroundcolor','blue');
    end;
end
clear version;

if get(check1,'value')&get(check2,'value')
   set(BottStart,'enable','on');
end;
