function info;
%crea la finestra di informazione collegata al corrispondente
%bottone del menu Help
%
%Massimo Davini 05/10/2000
%Revised by giampy several times

% enlarge text if java machine is running
global stack
jsz=stack.general.javasize;

pos=get(gcf,'position');
posnew=[pos(1)+pos(3)/4-.07,pos(2)+pos(4)/6-.05, pos(3)/2+.14 ,2*pos(4)/3+.1];

i(1)=figure('unit','normalized','WindowStyle','modal',...
   'position',posnew,'resize','off','Name','   About MimoTool',...
   'color',[0.6 0.6 0.9],'NumberTitle','off','menubar','none',...
   'CloseRequestFcn','delete(gcf);','visible','off'); 

[x,map]=imread('logo07','jpg');
h=image(x);

set(gca,'position',[0.17 0.78 0.66 0.18],'visible','off');

backg=[1 1 1];

i(2)=uicontrol('style','frame',...
   'unit','normalized','position',[0.04 0.04 0.92 0.7],...
   'backgroundcolor',backg);

i(3)=uicontrol('style','text',...
   'unit','normalized','position',[0.07 0.61 0.86 0.07],...
   'fontunits','normalized','fontsize',jsz*0.8+.8,'fontweight','bold',...
   'backgroundcolor',backg,'Horizontalalignment','center',...
   'string','MIMO TOOL','visible','on',...
   'foregroundcolor','red','fontname','times new roman');

i(4)=uicontrol('style','text',...
   'unit','normalized','position',[0.07 0.54 0.86 0.07],...
   'fontunits','normalized','fontsize',jsz/2+.6,'fontweight','bold',...
   'backgroundcolor',backg,'Horizontalalignment','center',...
   'string','Version 2.0 (R11.1-R2009a), Apr 2009','visible','on');

str=['GUI for the Analysis and Synthesis of'];
i(5)=uicontrol('style','text',...
   'unit','normalized','position',[0.06 0.42 0.88 0.06],...
   'fontunits','normalized','fontsize',jsz/2+.6,'fontweight','bold',...
   'backgroundcolor',backg,'Horizontalalignment','center',...
   'string',str,'visible','on');

str=['Linear, Multivariable, Continuous Time Systems.'];
i(6)=uicontrol('style','text',...
   'unit','normalized','position',[0.06 0.36 0.88 0.06],...
   'fontunits','normalized','fontsize',jsz/2+.6,'fontweight','bold',...
   'backgroundcolor',backg,'Horizontalalignment','center',...
   'string',str,'visible','on');

i(7)=uicontrol('style','text',...
   'unit','normalized','position',[0.06 0.23 0.88 0.06],...
   'fontunits','normalized','fontsize',jsz/2+.6,'fontweight','bold',...
   'backgroundcolor',backg,'Horizontalalignment','center',...
   'string','M. Davini , G. Campa , M. Innocenti','visible','on',...
   'foregroundcolor','blue');

str=['Department of Electrical Systems and Automation'];
i(8)=uicontrol('style','text',...
   'unit','normalized','position',[0.06 0.17 0.88 0.06],...
   'fontunits','normalized','fontsize',jsz/2+.6,'fontweight','bold',...
   'backgroundcolor',backg,'Horizontalalignment','center',...
   'string',str,'visible','on','foregroundcolor','blue');

str=['( DSEA ) , University of Pisa , 56126 Pisa , Italy .'];
i(9)=uicontrol('style','text',...
   'unit','normalized','position',[0.06 0.11 0.88 0.06],...
   'fontunits','normalized','fontsize',jsz/2+.6,'fontweight','bold',...
   'backgroundcolor',backg,'Horizontalalignment','center',...
   'string',str,'visible','on','foregroundcolor','blue');

set(i(1),'visible','on');
