function ea_2;

global stack;
set(stack.temp.handles,'visible','off');
drawnow;

% enlarge text if java machine is running
jsz=stack.general.javasize;

ea(1)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',jsz/2+.35,'fontweight','bold',...
   'Horizontalalignment','center','string','COMPUTE EIG \ ASSIGN',...
   'position',[0.55 0.85 0.4 0.1],'callback','ea_3;','tag','BREG');

ea(2)=uicontrol('style','push','unit','normalized','position',[0.05 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'string','BACK','Horizontalalignment','center','tag','BottBC',...
   'TooltipString','Back to the previous window','userdata',sprintf('feval(''back_syn'',''ea1'',%u)',length(stack.temp.handles)),...
   'callback',sprintf('if stack.general.K_flag messag(gcf,''kns'',''back'');else back_syn(''ea1'',%u);end;',length(stack.temp.handles)));

campi=['''constrain'',''tipo'',''num_autov'',''cont_autov'',''a_val'',''a_vet'',''flag'',''ach_vet'',''cla_val'',''cla_vet'''];
ea(3)=uicontrol('style','push','unit','normalized','position',[0.2 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
    'string','CLOSE','Horizontalalignment','center','tag','BottBC',...
    'TooltipString','Back to the main SYNTHESIS window','userdata',sprintf('feval(''back_syn'',''syn0'',0,%s)',campi),...
    'callback',sprintf('if stack.general.K_flag messag(gcf,''kns'',''close'');else back_syn(''syn0'',0,%s);end;',campi));

ea(4)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'TooltipString','Evaluate the computed Controller',...
   'Horizontalalignment','center','string','EVALUATION',...
   'position',[0.39 0.05 0.275 0.12],...
   'callback','valuta;','tag','BEVAL','enable','off');

ea(5)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'TooltipString','Open the SIMULINK Closed-Loop-System',...
   'Horizontalalignment','center','string','SIMULATION',...
   'position',[0.675 0.05 0.275 0.12],...
   'callback','simula;','tag','BSIMU','enable','off');

drawnow;

ea(6)=uicontrol('style','Frame','units','normalized','position',[0.05 0.22 0.29 0.73],...
   'backgroundcolor',[1 1 1],'tag','ea2');

ea(7)=uicontrol('style','text','units','normalized','position',[.06 .85 .27 0.05],...
   'fontunits','normalized','fontsize',jsz/2+.7,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','on','foregroundcolor','red',...
   'HorizontalAlignment','center','tag','ea2','string','VIEW ON MATLAB');

ea(8)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',jsz/4+.35,'fontweight','bold',...
   'Horizontalalignment','center','string','Desidered Eig.Val.',...
   'position',[0.06 0.68 0.27 0.1],...
   'callback','ea_2v(1);','tag','ea2');

ea(9)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',jsz/4+.35,'fontweight','bold',...
   'Horizontalalignment','center','string','Desidered Eig.Vec.',...
   'position',[0.06 0.57 0.27 0.1],...
   'callback','ea_2v(2);','tag','ea2');

ea(10)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',jsz/4+.35,'fontweight','bold',...
   'Horizontalalignment','center','string','Achievable Eig.Vec.',...
   'position',[0.06 0.46 0.27 0.1],...
   'callback','ea_2v(3);','tag','ea2');

ea(11)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',jsz/3+.35,'fontweight','bold',...
   'Horizontalalignment','center','string','Closed-loop Eig.Val.',...
   'position',[0.06 0.35 0.27 0.1],...
   'callback','ea_2v(4);','tag','cla','enable','off');

ea(12)=uicontrol('style','push','unit','normalized',...
   'fontunits','normalized','fontsize',jsz/2+.35,'fontweight','bold',...
   'Horizontalalignment','center','string','Closed-loop Eig.Vec.',...
   'position',[0.06 0.24 0.27 0.1],...
   'callback','ea_2v(5);','tag','cle','enable','off');


drawnow;
%aggiornamento handles temporanei
stack.temp.handles=[stack.temp.handles,ea];