function h0(tipo,n,pesi)
%H0 : 1° finestra di sintesi e di ottimizzazione  H2 o H-INFINITY
%
%                     h0(tipo,n,pesi)
%
%  tipo  = stringa indicante il tipo di sintesi o di ottimizzazione
%          scelta : 'H - 2' o 'H - INFINITY'
%
%  n     = intero che indica il numero di blocchi di integratori
%          da aggiungere al sistema
%          (presente sia in caso di sintesi che di ottimizzazione)
%
%  pesi  = vettore riga di 4 elementi rappresentanti i pesi
%          della funzione di costo da minimizzare : vedi il manuale
%          per maggiori informazioni
%          (presente solo in caso di ottimizzazione)
%
%
% Massimo Davini 27/05/99 --- revised 31/05/99
global stack;

if nargin<3 pesi=[];end;
set(findobj('tag','integratori'),'visible','off');
set(findobj('tag','EditIntegr'),'visible','off');
drawnow;

stack.temp.integratori=n;
stack.temp.pesi=pesi;

% enlarge text if java machine is running
jsz=stack.general.javasize;

sizetext1=jsz*0.5+.6;
h0(1)=uicontrol('style','frame','units','normalized','position',[0.1 0.32 0.8 0.53],...
    'backgroundcolor',[1 1 1],'visible','off','tag','h0');
 
h0(2)=uicontrol('style','text','units','normalized','position',[0.12 0.72 0.76 0.06],...
   'fontunits','normalized','fontsize',sizetext1*1.1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'HorizontalAlignment','center','foregroundcolor','red',...
   'visible','off','string','Which matrices do you want to minimize ?','tag','h0');

h0(3)=uicontrol('style','radiobutton','units','normalized','position',[0.15 0.6 0.2 0.06],...
   'fontunits','normalized','fontsize',sizetext1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','value',1,...
   'HorizontalAlignment','left','string',' [ To ; So ]',...
   'callback','sldopt(1,''opt1'',''opt2'');','tag','opt1');

h0(4)=uicontrol('style','text','units','normalized','position',[0.18 0.54 0.7 0.06],...
   'fontunits','normalized','fontsize',sizetext1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','HorizontalAlignment','left',...
   'string','COMPLEMENTARY SENSITIVITY and SENSITIVITY','tag','h0');

h0(5)=uicontrol('style','radiobutton','units','normalized','position',[0.15 0.44 0.4 0.06],...
   'fontunits','normalized','fontsize',sizetext1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','HorizontalAlignment','left',...
   'string',' [ Mo ; So ]','tag','opt2',...
   'callback','sldopt(2,''opt1'',''opt2'');');

h0(6)=uicontrol('style','text','units','normalized','position',[0.18 0.38 0.7 0.06],...
   'fontunits','normalized','fontsize',sizetext1,'fontweight','bold',...
   'backgroundcolor',[1 1 1],'visible','off','HorizontalAlignment','left',...
   'string','CONTROL SENSITIVITY and SENSITIVITY','tag','h0');
 
h0(7)=uicontrol('style','push','unit','normalized','position',[0.05 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'string','BACK','Horizontalalignment','center','tag','h0',...
   'TooltipString','Back to the previous window',...
   'callback',sprintf('back_syn(''integratori'',%u,''integratori'',''pesi'');',length(stack.temp.handles))); 

h0(8)=uicontrol('style','push','unit','normalized','position',[0.2 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'string','CLOSE','Horizontalalignment','center',...
   'TooltipString','Back to the main SYNTHESIS window',...
   'callback','back_syn(''syn0'',0,''integratori'',''pesi'');','tag','h0');
 
h0(9)=uicontrol('style','push','unit','normalized','position',[0.81 0.05 0.14 0.12],...
   'fontunits','normalized','fontsize',.35,'fontweight','bold',...
   'Horizontalalignment','center','string','NEXT','tag','h0',...
   'TooltipString','Go to the next window','callback',sprintf('h1(''%s'');',tipo));

set(h0,'visible','on');
drawnow;

stack.temp.handles=[stack.temp.handles,h0];